groupName: acme.fsvm88.me
logLevel: 6
certManager:
  namespace: cert-manager
  serviceAccountName: cert-manager
image:
  repository: fsvm88/cert-manager-webhook-gandi
  tag: 0.2.0
  pullPolicy: IfNotPresent
nameOverride: ""
fullnameOverride: ""
service:
  type: ClusterIP
  port: 443
features:
  apiPriorityAndFairness: false
resources: {}
nodeSelector: {}
tolerations: []
affinity: {}
